<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>problem_6_22_23jul</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Views\Automobile\" />
  </ItemGroup>

</Project>
